# Use Node Alpine base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy app files  
COPY . .

# Install dependencies  
RUN npm install

# Expose port 3000
EXPOSE 3000   

# Start app
CMD ["node", "test.js"]