FROM node:16-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000   

CMD ["node", "test.js"]

# FROM node:16-alpine

# WORKDIR /app

# COPY . .

# RUN npm install

# EXPOSE 3000   

# CMD ["node", "test.js"]