
FROM python:3.7-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /app  

EXPOSE 8000  

CMD ["python", "main.py"]


# FROM python:3.7-slim

# WORKDIR /app

# COPY . /app  

# # RUN pip install --trusted-host pypi.python.org flask flask_cors pymongo
# # RUN pip install flask flask_cors pymongo
# RUN pip install -r requirements.txt


# EXPOSE 8000  

# CMD ["python", "main.py"]
