# Use an official Python runtime as a parent image 
FROM python:3.7-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app  

# Install dependencies
RUN pip install --trusted-host pypi.python.org flask flask_cors pymongo

# Make port 8000 available 
EXPOSE 8000  

# Run app.py when the container launches
CMD ["python", "main.py"]